add configure code

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -1,4 +1,13 @@
 #!/bin/sh
 # this uses golang because I don't like shell scripts
 # if you need to fix stuff, change it in the configure.go
-go run cmd/configure/configure.go
+
+GO_BIN=$(which go)
+
+# Check if Go is installed by verifying if GO_BIN is not empty
+if [ -z "$GO_BIN" ]; then
+    echo "Go is not installed or not found in the PATH."
+    exit 1
+fi
+
+sudo $GO_BIN run cmd/configure/configure.go
